# Use the official Node.js image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

RUN corepack enable
COPY ./server/package.json ./
COPY ./pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY ./server/ . ./



# Build the NestJS application
RUN pnpm run build

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["node", "dist/src/main"]