name: Build and Deploy Test Server

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor via HTTPS
        uses: docker/login-action@v3
        with:
          registry: ibuidl-harbor.duckdns.org:8443
          username: admin
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ibuidl-harbor.duckdns.org:8443/pozoko/pozoko-server-dev:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.170.154.11
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" 
            mkdir -p ~/deploy/pozoko_server_dev
            docker login -u admin -p ${{ secrets.HARBOR_PASSWORD }} ibuidl-harbor.duckdns.org:8443
            echo "${{ secrets.ENV_PRO_BASE64 }}" | base64 --decode > ~/deploy/pozoko_server_dev/.env.pro


            cat << 'EOF' > ~/deploy/pozoko_server_dev/docker-compose.yml
            ${{ vars.DEV_SERVER_COMPOSE_FILE }}
            EOF
            cd ~/deploy/pozoko_server_dev
            docker compose up -d --remove-orphans
